// app/login/page.tsx
"use client"

import type React from "react"

import { createClient } from "@/lib/supabase/client"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { useState } from "react"
import { Loader2 } from "lucide-react"

export default function LoginPage() {
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [error, setError] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const router = useRouter()

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault()
    const supabase = createClient()
    setIsLoading(true)
    setError(null)

    try {
      const { error } = await supabase.auth.signInWithPassword({
        email,
        password,
      })
      if (error) throw error
      router.push("/dashboard")
      router.refresh()
    } catch (error: unknown) {
      setError(error instanceof Error ? error.message : "Erro ao fazer login. Verifique suas credenciais.")
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="flex min-h-screen w-full items-center justify-center bg-gradient-to-br from-blue-50 via-white to-purple-50 p-6">
      <div className="w-full max-w-md">
        <div className="mb-8 text-center">
          <h1 className="text-4xl font-bold text-gray-900 mb-2">Portal Direx</h1>
          <p className="text-gray-600">Sistema de Gestão Empresarial</p>
        </div>

        <Card className="shadow-xl border-gray-200">
          <CardHeader className="space-y-1">
            <CardTitle className="text-2xl font-bold text-center">Acesse sua conta</CardTitle>
            <CardDescription className="text-center">Digite suas credenciais para acessar o sistema</CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleLogin}>
              <div className="flex flex-col gap-4">
                <div className="grid gap-2">
                  <Label htmlFor="email">E-mail</Label>
                  <Input
                    id="email"
                    type="email"
                    placeholder="seu@email.com"
                    required
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    disabled={isLoading}
                    className="h-11"
                  />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="password">Senha</Label>
                  <Input
                    id="password"
                    type="password"
                    placeholder="••••••••"
                    required
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    disabled={isLoading}
                    className="h-11"
                  />
                </div>
                {error && (
                  <div className="rounded-md bg-red-50 border border-red-200 p-3">
                    <p className="text-sm text-red-600">{error}</p>
                  </div>
                )}
                <Button type="submit" className="w-full h-11 bg-blue-600 hover:bg-blue-700" disabled={isLoading}>
                  {isLoading ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Entrando...
                    </>
                  ) : (
                    "Entrar"
                  )}
                </Button>
              </div>
              <div className="mt-6 text-center text-sm">
                <span className="text-gray-600">Não tem uma conta? </span>
                <Link
                  href="/cadastro"
                  className="font-semibold text-blue-600 hover:text-blue-700 underline underline-offset-4"
                >
                  Cadastre-se
                </Link>
              </div>
            </form>
          </CardContent>
        </Card>

        <div className="mt-8 text-center text-xs text-gray-500">
          <p>© 2025 Portal Direx. Todos os direitos reservados.</p>
        </div>
      </div>
    </div>
  )
}

// portal-direx/frontend/src/app/features/auth/login/login.component.ts
import { Component, inject } from "@angular/core"
import { CommonModule } from "@angular/common"
import { FormsModule } from "@angular/forms"
import { Router, RouterLink } from "@angular/router"
import { AuthService } from "../../../core/services/auth.service"

@Component({
  selector: "app-login",
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: "./login.component.html",
  styleUrl: "./login.component.css",
})
export class LoginComponent {
  private authService = inject(AuthService)
  private router = inject(Router)

  email = ""
  senha = ""
  error = ""
  isLoading = false

  onSubmit(): void {
    if (!this.email || !this.senha) {
      this.error = "Preencha todos os campos"
      return
    }

    this.isLoading = true
    this.error = ""

    this.authService.login({ email: this.email, senha: this.senha }).subscribe({
      next: () => {
        this.router.navigate(["/dashboard"])
      },
      error: (err) => {
        this.error = err.error?.message || "Erro ao fazer login. Verifique suas credenciais."
        this.isLoading = false
      },
    })
  }
}

<div class="login-container">
  <div class="login-box">
    <div class="header">
      <h1>Portal Direx</h1>
      <p>Sistema de Gestão Empresarial</p>
    </div>

    <div class="card">
      <div class="card-header">
        <h2>Acesse sua conta</h2>
        <p>Digite suas credenciais para acessar o sistema</p>
      </div>

      <form (ngSubmit)="onSubmit()" class="form">
        <div class="form-group">
          <label for="email">E-mail</label>
          <input
            id="email"
            type="email"
            [(ngModel)]="email"
            name="email"
            placeholder="seu@email.com"
            required
            [disabled]="isLoading"
            class="input"
          />
        </div>

        <div class="form-group">
          <label for="senha">Senha</label>
          <input
            id="senha"
            type="password"
            [(ngModel)]="senha"
            name="senha"
            placeholder="••••••••"
            required
            [disabled]="isLoading"
            class="input"
          />
        </div>

        <div *ngIf="error" class="error-message">
          {{ error }}
        </div>

        <button type="submit" class="submit-btn" [disabled]="isLoading">
          <span *ngIf="!isLoading">Entrar</span>
          <span *ngIf="isLoading">Entrando...</span>
        </button>

        <div class="signup-link">
          <span>Não tem uma conta? </span>
          <a routerLink="/cadastro">Cadastre-se</a>
        </div>
      </form>
    </div>

    <div class="footer">
      <p>© 2025 Portal Direx. Todos os direitos reservados.</p>
    </div>
  </div>
</div>
