// app/cadastro/page.tsx
"use client"

import type React from "react"

import { createClient } from "@/lib/supabase/client"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { useState } from "react"
import { Loader2 } from "lucide-react"

export default function CadastroPage() {
  const [fullName, setFullName] = useState("")
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [confirmPassword, setConfirmPassword] = useState("")
  const [error, setError] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const router = useRouter()

  const handleSignUp = async (e: React.FormEvent) => {
    e.preventDefault()
    const supabase = createClient()
    setIsLoading(true)
    setError(null)

    if (password !== confirmPassword) {
      setError("As senhas não coincidem")
      setIsLoading(false)
      return
    }

    if (password.length < 6) {
      setError("A senha deve ter pelo menos 6 caracteres")
      setIsLoading(false)
      return
    }

    try {
      const { error } = await supabase.auth.signUp({
        email,
        password,
        options: {
          emailRedirectTo: process.env.NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL || `${window.location.origin}/dashboard`,
          data: {
            full_name: fullName,
          },
        },
      })
      if (error) throw error
      router.push("/cadastro-sucesso")
    } catch (error: unknown) {
      setError(error instanceof Error ? error.message : "Erro ao criar conta. Tente novamente.")
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="flex min-h-screen w-full items-center justify-center bg-gradient-to-br from-blue-50 via-white to-purple-50 p-6">
      <div className="w-full max-w-md">
        <div className="mb-8 text-center">
          <h1 className="text-4xl font-bold text-gray-900 mb-2">Portal Direx</h1>
          <p className="text-gray-600">Sistema de Gestão Empresarial</p>
        </div>

        <Card className="shadow-xl border-gray-200">
          <CardHeader className="space-y-1">
            <CardTitle className="text-2xl font-bold text-center">Criar nova conta</CardTitle>
            <CardDescription className="text-center">Preencha os dados abaixo para se cadastrar</CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSignUp}>
              <div className="flex flex-col gap-4">
                <div className="grid gap-2">
                  <Label htmlFor="fullName">Nome completo</Label>
                  <Input
                    id="fullName"
                    type="text"
                    placeholder="Seu nome completo"
                    required
                    value={fullName}
                    onChange={(e) => setFullName(e.target.value)}
                    disabled={isLoading}
                    className="h-11"
                  />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="email">E-mail</Label>
                  <Input
                    id="email"
                    type="email"
                    placeholder="seu@email.com"
                    required
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    disabled={isLoading}
                    className="h-11"
                  />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="password">Senha</Label>
                  <Input
                    id="password"
                    type="password"
                    placeholder="Mínimo 6 caracteres"
                    required
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    disabled={isLoading}
                    className="h-11"
                  />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="confirmPassword">Confirmar senha</Label>
                  <Input
                    id="confirmPassword"
                    type="password"
                    placeholder="Digite a senha novamente"
                    required
                    value={confirmPassword}
                    onChange={(e) => setConfirmPassword(e.target.value)}
                    disabled={isLoading}
                    className="h-11"
                  />
                </div>
                {error && (
                  <div className="rounded-md bg-red-50 border border-red-200 p-3">
                    <p className="text-sm text-red-600">{error}</p>
                  </div>
                )}
                <Button type="submit" className="w-full h-11 bg-blue-600 hover:bg-blue-700" disabled={isLoading}>
                  {isLoading ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Criando conta...
                    </>
                  ) : (
                    "Criar conta"
                  )}
                </Button>
              </div>
              <div className="mt-6 text-center text-sm">
                <span className="text-gray-600">Já tem uma conta? </span>
                <Link
                  href="/login"
                  className="font-semibold text-blue-600 hover:text-blue-700 underline underline-offset-4"
                >
                  Faça login
                </Link>
              </div>
            </form>
          </CardContent>
        </Card>

        <div className="mt-8 text-center text-xs text-gray-500">
          <p>© 2025 Portal Direx. Todos os direitos reservados.</p>
        </div>
      </div>
    </div>
  )
}

// portal-direx/frontend/src/app/features/auth/cadastro/cadastro.component.ts
import { Component, inject } from "@angular/core"
import { CommonModule } from "@angular/common"
import { FormsModule } from "@angular/forms"
import { Router, RouterLink } from "@angular/router"
import { AuthService } from "../../../core/services/auth.service"

@Component({
  selector: "app-cadastro",
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: "./cadastro.component.html",
  styleUrl: "./cadastro.component.css",
})
export class CadastroComponent {
  private authService = inject(AuthService)
  private router = inject(Router)

  nome = ""
  email = ""
  senha = ""
  confirmarSenha = ""
  error = ""
  isLoading = false

  onSubmit(): void {
    if (!this.nome || !this.email || !this.senha || !this.confirmarSenha) {
      this.error = "Preencha todos os campos"
      return
    }

    if (this.senha !== this.confirmarSenha) {
      this.error = "As senhas não coincidem"
      return
    }

    if (this.senha.length < 6) {
      this.error = "A senha deve ter no mínimo 6 caracteres"
      return
    }

    this.isLoading = true
    this.error = ""

    this.authService
      .cadastro({
        nome: this.nome,
        email: this.email,
        senha: this.senha,
      })
      .subscribe({
        next: () => {
          this.router.navigate(["/dashboard"])
        },
        error: (err) => {
          this.error = err.error?.message || "Erro ao criar conta. Tente novamente."
          this.isLoading = false
        },
      })
  }
}

<div class="cadastro-container">
  <div class="cadastro-box">
    <div class="header">
      <h1>Portal Direx</h1>
      <p>Sistema de Gestão Empresarial</p>
    </div>

    <div class="card">
      <div class="card-header">
        <h2>Crie sua conta</h2>
        <p>Preencha os dados abaixo para se cadastrar</p>
      </div>

      <form (ngSubmit)="onSubmit()" class="form">
        <div class="form-group">
          <label for="nome">Nome completo</label>
          <input
            id="nome"
            type="text"
            [(ngModel)]="nome"
            name="nome"
            placeholder="Seu nome completo"
            required
            [disabled]="isLoading"
            class="input"
          />
        </div>

        <div class="form-group">
          <label for="email">E-mail</label>
          <input
            id="email"
            type="email"
            [(ngModel)]="email"
            name="email"
            placeholder="seu@email.com"
            required
            [disabled]="isLoading"
            class="input"
          />
        </div>

        <div class="form-group">
          <label for="senha">Senha</label>
          <input
            id="senha"
            type="password"
            [(ngModel)]="senha"
            name="senha"
            placeholder="••••••••"
            required
            [disabled]="isLoading"
            class="input"
          />
        </div>

        <div class="form-group">
          <label for="confirmarSenha">Confirmar senha</label>
          <input
            id="confirmarSenha"
            type="password"
            [(ngModel)]="confirmarSenha"
            name="confirmarSenha"
            placeholder="••••••••"
            required
            [disabled]="isLoading"
            class="input"
          />
        </div>

        <div *ngIf="error" class="error-message">
          {{ error }}
        </div>

        <button type="submit" class="submit-btn" [disabled]="isLoading">
          <span *ngIf="!isLoading">Cadastrar</span>
          <span *ngIf="isLoading">Cadastrando...</span>
        </button>

        <div class="login-link">
          <span>Já tem uma conta? </span>
          <a routerLink="/login">Faça login</a>
        </div>
      </form>
    </div>

    <div class="footer">
      <p>© 2025 Portal Direx. Todos os direitos reservados.</p>
    </div>
  </div>
</div>
